<a href="https://colab.research.google.com/github/Fatai-soliu/Housepricing/blob/main/Advanced_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Iterator

list = [1,2,3,4,5,6]

In [ ]:
type(list)

list

In [ ]:
print(list)

[1, 2, 3, 4, 5, 6]


In [ ]:
my_list = list
for i in my_list:
  print(i)

1
2
3
4
5
6


In [ ]:
iter(my_list)

In [ ]:
iterator = iter(my_list)

In [ ]:
print(type(iterator))

<class 'list_iterator'>


In [ ]:
print(iterator)

In [ ]:
## To handle exception
try:
  print(next(iterator))
except StopIteration:
  print("There is no numbers left in the iterator")

There is no numbers left in the iterator


In [ ]:
# Same thing for string

#my_string = "Hello"
#string_iterator = iter(my_string)

try:
  print(next(string_iterator))
except StopIteration:
  print("There are no alphabets left to iterate on")

There are no alphabets left to iterate on


In [ ]:
## Generators
def square(n):
    for i in range(3):
        yield i**2


In [ ]:
square(3)

<generator object square at 0x78bb6d05d5b0>

In [ ]:
for i in square(3):
  print(i)

0
1
4


In [ ]:
a=square(3)
a

<generator object square at 0x78bb6d05d690>

In [ ]:
next(a)

4

In [ ]:
def my_generator():
  yield 1
  yield 2
  yield 3


In [ ]:
gen = my_generator()
gen

<generator object my_generator at 0x78bb6d05dc40>

In [ ]:
next(gen)

1

In [ ]:
for val in gen:
  print(val)

2
3


### Practical Example: Reading Large Files

Generators are particularly useful for reading large files because they allow you to process one line at a time without loading the entire file into memory

In [ ]:
## Pratical example : Reading Large files

def read_large_file(file_path):
  with open(file_path, 'r') as file:
    for line in file:
      yield line


In [ ]:
file_path = 'large_file.txt' ## create a large file and test

for line in read_large_file(file_path):
    print(line.strip())

Data Analysis with Python

In [1]:
!pip install numpy

In [3]:
import numpy as np

## Create arrays using numpy
##Create a 1D array

arr1  = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr2 = np.array([1,2,3,4,5])


array([[1, 2, 3, 4, 5]])

In [14]:
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [12]:
arr2.shape

(5,)

In [18]:
##2D Array

arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [19]:
print(arr3.shape)
print(arr3)

(2, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
#Array with in built function

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## Numpy Vectorized Operation

arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

## Elemenet wise addition
print("Addition:", arr4+arr5)

##Element wise substraction
print("Substration:", arr4-arr5)

Addition: [11 22 33 44 55]
Substration: [ -9 -18 -27 -36 -45]


In [25]:
## Universal function
##square root
print(np.sqrt(arr4))

##Exponential
print(np.exp(arr4))

#Sine
print(np.sin(arr4))

#Natural Log
print(np.log(arr4))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
## Array slicing and indexing

arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array /n:", arr6)

Array /n: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr6[0][0])
print(arr6[1:,2:])

1
[[ 7  8]
 [11 12]]


In [40]:
print(arr6[1:,1:3])

[[ 6  7]
 [10 11]]


In [41]:
## Statistical concept -- Normalization
##To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

In [42]:
print(mean)
print(std_dev)

3.0
1.4142135623730951


In [48]:
##Normalize the data

normalized_data = (data - mean)/ std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
## Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

data[(data>5) & (data <10)]

array([6, 7, 8, 9])